name: ysa_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+8

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Imágenes
  image_picker: ^1.1.2
  cloudinary_public: ^0.21.0
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.3.0

  url_launcher: ^6.3.1

  # Generar Reportes
  pdf: ^3.10.7  
  printing: ^5.12.0
  path_provider: ^2.1.2  
  
  #FIREBASE
  collection: ^1.19.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.1.5
  firebase_storage: ^12.4.6
  flutter_local_notifications: ^18.0.1
  
  provider: 6.1.5
  intl: ^0.20.2
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

# Configuración del icono de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/splash_logo3.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/splash_logo3.png"

# Configuración del Splash Screen
flutter_native_splash:
  # Color de fondo (blanco, cambia a #D9266D para rosa)
  color: "#FFFFFF"
  
  # Imagen del logo
  image: assets/splash_logo4.png
  
  # Plataformas
  android: true
  ios: true
  web: false
  
  # Configuración Android
  android_gravity: center
  fullscreen: true
  
  # Configuración Android 12+
  android_12:
    image: assets/splash_logo4.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true
  
  assets:
    - assets/