// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEj3SMjjpqFHJk6C-bNAz7BNo1U8b7HhQ',
    appId: '1:1016582440272:web:360464604328f402ce1855',
    messagingSenderId: '1016582440272',
    projectId: 'ysapp-18960',
    authDomain: 'ysapp-18960.firebaseapp.com',
    storageBucket: 'ysapp-18960.firebasestorage.app',
    measurementId: 'G-7BWEFF7XZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAidzbfPXzd_XxRGwvRB2kNQzJbxgKJed8',
    appId: '1:1016582440272:android:608ade020410350dce1855',
    messagingSenderId: '1016582440272',
    projectId: 'ysapp-18960',
    storageBucket: 'ysapp-18960.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrXRYCrSm0aQebcPAQeFqYVrpwf38mI2c',
    appId: '1:1016582440272:ios:c0a4af142cca488ece1855',
    messagingSenderId: '1016582440272',
    projectId: 'ysapp-18960',
    storageBucket: 'ysapp-18960.firebasestorage.app',
    iosBundleId: 'com.example.ysaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrXRYCrSm0aQebcPAQeFqYVrpwf38mI2c',
    appId: '1:1016582440272:ios:c0a4af142cca488ece1855',
    messagingSenderId: '1016582440272',
    projectId: 'ysapp-18960',
    storageBucket: 'ysapp-18960.firebasestorage.app',
    iosBundleId: 'com.example.ysaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEj3SMjjpqFHJk6C-bNAz7BNo1U8b7HhQ',
    appId: '1:1016582440272:web:b64f0b9e95bad3fdce1855',
    messagingSenderId: '1016582440272',
    projectId: 'ysapp-18960',
    authDomain: 'ysapp-18960.firebaseapp.com',
    storageBucket: 'ysapp-18960.firebasestorage.app',
    measurementId: 'G-RZGJW4E984',
  );

}